### PR TITLE
Use a non bundled entry

### PR DESCRIPTION
**Pull request by jschr**
Using a non bundled entry allows the consuming webpack bundle to do more optimizations. 

You can still require the bundle with require('schedule-utilities/dist/schedule-utilities') but this is no longer the default.

Doing this for schedule-utilities and elements brings the dash bundle size down from 2.14mb -> 1.81mb (15% savings).

### CODE REVIEW

**Comment by AttackTheDarkness** [comment]
I wonder if we can optimize further by including a smaller library... IIRC we're only using timezone xlation functionality of Moment, so there's a lot of code there that should be going unused.

**Review by AttackTheDarkness — APPROVED** [review]
Approving because 300K savings is worth it, but I feel like this change damages the DX of the library. I'll enter an Asana task to revisit later (which will probably involve yanking Moment).

**Comment by KiaFathi** [comment]
@AttackTheDarkness : What does DX stand for?

**Comment by AttackTheDarkness** [comment]
"developer experience"

**Comment by AttackTheDarkness** [comment]
Also, "deluxe" if appended to "Mario Kart 8" and/or "Pokken Tournament"

**Review by KiaFathi — CHANGES_REQUESTED** [review]
Can we explicate the two methods of importing this library in the readme?

**Comment by jschr** [comment]
@KiaFathi @AttackTheDarkness Can you guys think of a use case for having both? What do you think about removing the bundled import?

**Comment by AttackTheDarkness** [comment]
It's generally considered bad manners to assume library consumers have an ES6 / Babel workflow set up to consume your stuff. While we're the only consumers it is no big deal, but if we want devs outside of Mira to use this, we should try to make it as flexible/easy as possible.

**Comment by jschr** [comment]
This change compiles with babel before publishing to npm so there shouldn't be that assumption. The only assumption is if you want to use this lib in the browser, you should use a bundler (Webpack, Browserify, etc...)

Importing via `lib` as opposed to `dist` should be the norm AFAIK, especially if using in Node. Error messages will be easier to debug since it will report the file that it occurred in rather than the bundle.

**Comment by KiaFathi** [comment]
@jschr: I think it would be good manners to have both, especially since this is a public repo. It's very little additional work on our end to provide that option.

**Comment by jschr** [comment]
@KiaFathi Readme updated!

**Review by KiaFathi — APPROVED** [review]

**Pull request merged**
